apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-shift-app-deployment
spec:
  selector:
    matchLabels:
      app: open-shift-app
  replicas: 1
  template:
    metadata:
      labels:
        app: open-shift-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: open-shift-app
          image: docker.io/elkpuchon/quarkus-openshift
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080