apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-shift-app-deployment
spec:
  selector:
    matchLabels:
      app: open-shift-app
  replicas: 1
  template:
    metadata:
      labels:
        app: open-shift-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: open-shift-app
          image: docker.io/elkpuchon/quarkus-openshift
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
      
        - name: open-shift-mysql
          image: registry.redhat.io/rhscl/mysql-57-rhel7
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3306
          env:
            - name: "MYSQL_USER"
              value: "ccm"
            - name: "MYSQL_PASSWORD"
              value: "openshift2023"
            - name: "MYSQL_DATABASE"
              value: "mythology"
            - name: "MYSQL_ROOT_PASSWORD"
              value: "openshift2023"