apiVersion: v1
kind: Service
metadata:
  name: open-shift-app-service
spec:
  selector:
    app: open-shift-app
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: open-shift-mysql-service
spec:
  selector:
    app: open-shift-mysql
  ports:
    - port: 3306
      targetPort: 3306
  