name: Deploy the app on Docker registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy the app on OpenShift SandBox server

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
         oc_version: '4.6'

      - name : Login into docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image with maven
        run: |
            make build_image

      - name: Login on OpenShift Server 
        run: |
            oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}

      - name: Update kubeconfig
        run: |
          make update_deployment_image
